import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BookOpen, CalendarDays, Check, ClipboardList, Clock3, ListTodo, ChartNoAxesCombined, Sparkles, Timer, Target } from 'lucide-react';
import { Badge } from '@orbit/design-system';
import { Navbar } from '@/components/public/navbar';
import { Footer } from '@/components/public/footer';
import { FeatureCard } from '@/components/public/feature-card';
import { ProductPreview } from '@/components/public/product-preview';

export const metadata: Metadata = { title: 'Orbit — Seu foco em órbita', description: 'Plataforma para organizar estudos, matérias, tarefas, provas e sessões de foco.' };
const features = [
  { icon: BookOpen, title: 'Disciplinas', description: 'Uma visão clara das matérias e do progresso, com cards já disponíveis na prévia.' },
  { icon: CalendarDays, title: 'Calendário', description: 'Um espaço planejado para reunir aulas, compromissos e datas importantes.' },
  { icon: ListTodo, title: 'Tarefas', description: 'Listas e prazos para transformar grandes objetivos em pequenos passos.' },
  { icon: ClipboardList, title: 'Provas', description: 'Avaliações em perspectiva, com tempo para se preparar com tranquilidade.' },
  { icon: Timer, title: 'Pomodoro', description: 'Prévia de sessões de foco. Temporizador e registro de sessões estão planejados.' },
  { icon: ChartNoAxesCombined, title: 'Estatísticas', description: 'Indicadores planejados para tornar sua constância e evolução visíveis.' },
  { icon: Sparkles, title: 'Plano inteligente', description: 'Uma futura camada de IA para apoiar seu planejamento de estudos.' },
];
export default function Home() {
  return <div className="public-site"><a className="skip-link" href="#main-content">Pular para o conteúdo</a><Navbar /><main id="main-content" tabIndex={-1}>
    <section className="hero public-container" aria-labelledby="hero-title"><div className="hero-orbit" aria-hidden="true" /><span className="hero-label"><span />SEU PRÓXIMO PASSO COMEÇA AQUI</span><h1 id="hero-title">Coloque seus estudos<br className="desktop-break" /> <span>em órbita.</span></h1><p>Organize matérias, provas, tarefas, horários e sessões de foco em um só lugar.</p><div className="hero-actions"><Link href="/cadastro" className="orbit-button orbit-button--primary">Começar agora <ArrowRight size={18} aria-hidden="true" /></Link><a href="#recursos" className="orbit-button orbit-button--secondary">Conhecer recursos</a></div><div className="hero-note"><Check size={15} aria-hidden="true" />Uma nova forma de planejar. Uma prévia para explorar.</div></section>
    <div className="public-container"><ProductPreview /></div>
    <section id="produtividade" className="public-section public-container" aria-labelledby="benefits-title"><div className="section-heading"><span className="section-eyebrow">MENOS RUÍDO. MAIS DIREÇÃO.</span><h2 id="benefits-title">Abra espaço para o seu foco.</h2><p>Uma rotina de estudos mais clara começa com tudo no lugar certo.</p></div><div className="benefits-grid"><FeatureCard icon={BookOpen} title="Organize tudo" description="A proposta é simples: matérias, tarefas, provas e horários em um só lugar." /><FeatureCard icon={Target} title="Estude com foco" description="Conheça a prévia do Pomodoro, pensado para estudar um passo de cada vez." /><FeatureCard icon={Clock3} title="Saiba o que priorizar" description="O dashboard apresenta uma visão de prazos e pendências com dados ilustrativos." /><FeatureCard icon={Sparkles} title="Planejamento inteligente" description="Uma interface preparada para futuros planos de estudo com IA." planned /></div></section>
    <section id="como-funciona" className="public-section steps-section" aria-labelledby="steps-title"><div className="public-container"><div className="section-heading"><span className="section-eyebrow">DO PLANO À CONSTÂNCIA</span><h2 id="steps-title">Seu ritmo. Seu caminho.</h2><p>Três passos que guiam a experiência que estamos construindo.</p></div><ol className="steps-grid">{[['Organize sua rotina', 'Reúna suas matérias e visualize os compromissos da semana.'], ['Planeje seus estudos', 'Defina prioridades e reserve espaço para cada objetivo.'], ['Acompanhe sua evolução', 'Entenda seu ritmo e ajuste o próximo passo com clareza.']].map(([title, description], i) => <li key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{description}</p></li>)}</ol></div></section>
    <section id="recursos" className="public-section public-container" aria-labelledby="features-title"><div className="section-heading"><span className="section-eyebrow">UM LUGAR PARA CADA PARTE DO SEU DIA</span><h2 id="features-title">Tudo conectado ao seu objetivo.</h2><p>Explore a fundação visual do Orbit. Os módulos serão ativados nas próximas etapas; os dados atuais são demonstrativos.</p></div><div className="features-grid">{features.map((feature, i) => <FeatureCard {...feature} planned={i > 0} key={feature.title} />)}</div></section>
    <section id="ia" className="public-container ai-section" aria-labelledby="ai-title"><div className="ai-copy"><Badge tone="primary"><Sparkles size={14} aria-hidden="true" />IA · Em breve</Badge><h2 id="ai-title">Um plano de estudos que evolui com você.</h2><p>Estamos preparando uma camada inteligente para ajudar você a decidir o próximo passo, respeitando sua rotina e seus objetivos.</p><p>No futuro, o Orbit poderá considerar datas de provas, tarefas, disponibilidade, histórico de estudos e prioridades para sugerir planos de estudo.</p><span className="ai-disclaimer">Conceito em desenvolvimento. Nenhuma IA está ativa nesta etapa.</span></div><div className="plan-concept"><div className="plan-concept-title"><Sparkles size={20} aria-hidden="true" /><strong>Conectando seu contexto</strong></div>{['Datas de provas e tarefas', 'Sua disponibilidade', 'Histórico de estudos', 'Suas prioridades'].map((label, i) => <div className="context-row" key={label}><span>0{i + 1}</span>{label}<Check size={16} aria-hidden="true" /></div>)}<div className="plan-output"><Target size={20} aria-hidden="true" /><div><strong>Um próximo passo mais claro</strong><p>Ilustração de um futuro plano personalizado</p></div></div></div></section>
    <section className="public-section public-container final-cta" aria-labelledby="cta-title"><span className="section-eyebrow">SEU FOCO MERECE UM NOVO ESPAÇO</span><h2 id="cta-title">Pronto para colocar seus<br className="desktop-break" /> estudos em órbita?</h2><p>Conheça o Orbit e dê o primeiro passo nessa jornada.</p><div className="hero-actions"><Link href="/cadastro" className="orbit-button orbit-button--primary">Criar conta <ArrowRight size={18} aria-hidden="true" /></Link><Link href="/login" className="orbit-button orbit-button--secondary">Entrar</Link></div><small>Telas de acesso em prévia. Autenticação disponível em uma etapa futura.</small></section>
  </main><Footer /></div>;
}
